// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = ContactFormSlice | ContactHeroSlice | ContactTimelineSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<AboutDocumentData>,
  "about",
  Lang
>;

type CasestudiesDocumentDataSlicesSlice = CaseStudiesSlice | CaseStudyHeaderSlice;

/**
 * Content for CaseStudies documents
 */
interface CasestudiesDocumentData {
  /**
   * Slice Zone field in *CaseStudies*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: casestudies.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CasestudiesDocumentDataSlicesSlice> /**
   * Meta Title field in *CaseStudies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: casestudies.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *CaseStudies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: casestudies.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *CaseStudies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: casestudies.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * CaseStudies document from Prismic
 *
 * - **API ID**: `casestudies`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CasestudiesDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<CasestudiesDocumentData>,
  "casestudies",
  Lang
>;

/**
 * Content for CaseStudy documents
 */
interface CasestudyDocumentData {
  /**
   * Logo field in *CaseStudy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: casestudy.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Image field in *CaseStudy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: casestudy.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *CaseStudy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: casestudy.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Content field in *CaseStudy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: casestudy.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField /**
   * slug field in *CaseStudy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: casestudy.slug
   * - **Tab**: meta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  slug: prismic.KeyTextField;
}

/**
 * CaseStudy document from Prismic
 *
 * - **API ID**: `casestudy`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CasestudyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<CasestudyDocumentData>,
  "casestudy",
  Lang
>;

type ContactDocumentDataSlicesSlice = ContactFormSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ContactDocumentData>,
  "contact",
  Lang
>;

type HomeDocumentDataSlicesSlice =
  | ContactFormSlice
  | HomeContactFormSlice
  | HomeTestimoniesSlice
  | HomeProjectsSlice
  | HomeServicesSlice
  | HomeHeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<HomeDocumentData>,
  "home",
  Lang
>;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PageDocumentData>,
  "page",
  Lang
>;

type PortfolioDocumentDataSlicesSlice = ProjectsSlice | PorfolioHeaderSlice;

/**
 * Content for Portfolio documents
 */
interface PortfolioDocumentData {
  /**
   * Slice Zone field in *Portfolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice> /**
   * Meta Title field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<PortfolioDocumentData>,
  "portfolio",
  Lang
>;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Name field in *Project*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: project.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Summary field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary: prismic.RichTextField;

  /**
   * Content field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField /**
   * Slug field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slug
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  slug: prismic.KeyTextField;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<ProjectDocumentData>,
  "project",
  Lang
>;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Service*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Description field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * isHome field in *Service*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: service.ishome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  ishome: prismic.BooleanField;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<ServiceDocumentData>,
  "service",
  Lang
>;

type ServicesDocumentDataSlicesSlice = ServicesSlice | ServicesHeaderSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ServicesDocumentData>,
  "services",
  Lang
>;

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice> /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: settings.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<SettingsDocumentData>,
  "settings",
  Lang
>;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Name field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Content field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * isHome field in *Testimonial*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: testimonial.ishome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  ishome: prismic.BooleanField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<TestimonialDocumentData>,
  "testimonial",
  Lang
>;

type TestimoniesDocumentDataSlicesSlice = TestimoniesSlice | TestimoniesHeaderSlice;

/**
 * Content for Testimonies documents
 */
interface TestimoniesDocumentData {
  /**
   * Slice Zone field in *Testimonies*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TestimoniesDocumentDataSlicesSlice> /**
   * Meta Title field in *Testimonies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: testimonies.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Testimonies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: testimonies.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Testimonies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Testimonies document from Prismic
 *
 * - **API ID**: `testimonies`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimoniesDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<TestimoniesDocumentData>,
  "testimonies",
  Lang
>;

export type AllDocumentTypes =
  | AboutDocument
  | CasestudiesDocument
  | CasestudyDocument
  | ContactDocument
  | HomeDocument
  | PageDocument
  | PortfolioDocument
  | ProjectDocument
  | ServiceDocument
  | ServicesDocument
  | SettingsDocument
  | TestimonialDocument
  | TestimoniesDocument;

/**
 * Default variation for CaseStudies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CaseStudies*
 */
type CaseStudiesSliceVariation = CaseStudiesSliceDefault;

/**
 * CaseStudies Shared Slice
 *
 * - **API ID**: `case_studies`
 * - **Description**: CaseStudies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSlice = prismic.SharedSlice<"case_studies", CaseStudiesSliceVariation>;

/**
 * Primary content in *CaseStudyHeader → Default → Primary*
 */
export interface CaseStudyHeaderSliceDefaultPrimary {
  /**
   * Header field in *CaseStudyHeader → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_header.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;
}

/**
 * Default variation for CaseStudyHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudyHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudyHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CaseStudyHeader*
 */
type CaseStudyHeaderSliceVariation = CaseStudyHeaderSliceDefault;

/**
 * CaseStudyHeader Shared Slice
 *
 * - **API ID**: `case_study_header`
 * - **Description**: CaseStudyHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudyHeaderSlice = prismic.SharedSlice<
  "case_study_header",
  CaseStudyHeaderSliceVariation
>;

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<"contact_form", ContactFormSliceVariation>;

/**
 * Primary content in *AboutHero → Default → Primary*
 */
export interface ContactHeroSliceDefaultPrimary {
  /**
   * Header field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_hero.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;

  /**
   * Content field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_hero.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.TitleField;

  /**
   * Link field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_hero.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutHero*
 */
type ContactHeroSliceVariation = ContactHeroSliceDefault;

/**
 * AboutHero Shared Slice
 *
 * - **API ID**: `contact_hero`
 * - **Description**: ContactHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeroSlice = prismic.SharedSlice<"contact_hero", ContactHeroSliceVariation>;

/**
 * Default variation for AboutTimeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactTimelineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *AboutTimeline*
 */
type ContactTimelineSliceVariation = ContactTimelineSliceDefault;

/**
 * AboutTimeline Shared Slice
 *
 * - **API ID**: `contact_timeline`
 * - **Description**: ContactTimeline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactTimelineSlice = prismic.SharedSlice<
  "contact_timeline",
  ContactTimelineSliceVariation
>;

/**
 * Default variation for HomeContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *HomeContactForm*
 */
type HomeContactFormSliceVariation = HomeContactFormSliceDefault;

/**
 * HomeContactForm Shared Slice
 *
 * - **API ID**: `home_contact_form`
 * - **Description**: HomeContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeContactFormSlice = prismic.SharedSlice<
  "home_contact_form",
  HomeContactFormSliceVariation
>;

/**
 * Primary content in *HomeHero → Default → Primary*
 */
export interface HomeHeroSliceDefaultPrimary {
  /**
   * Starter field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.starter
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  starter: prismic.RichTextField;

  /**
   * Header field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;

  /**
   * top_content field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.top_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_content: prismic.RichTextField;

  /**
   * bottom_content field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.bottom_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_content: prismic.RichTextField;

  /**
   * CTA_Link field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Image field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSlice = prismic.SharedSlice<"home_hero", HomeHeroSliceVariation>;

/**
 * Primary content in *HomeProjects → Default → Primary*
 */
export interface HomeProjectsSliceDefaultPrimary {
  /**
   * Header field in *HomeProjects → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_projects.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;
}

/**
 * Default variation for HomeProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeProjects*
 */
type HomeProjectsSliceVariation = HomeProjectsSliceDefault;

/**
 * HomeProjects Shared Slice
 *
 * - **API ID**: `home_projects`
 * - **Description**: HomeProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeProjectsSlice = prismic.SharedSlice<"home_projects", HomeProjectsSliceVariation>;

/**
 * Item in *HomeServices → Default → Primary → Services*
 */
export interface HomeServicesSliceDefaultPrimaryServicesItem {
  /**
   * Service Header field in *HomeServices → Default → Primary → Services*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_services.default.primary.services[].service_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_header: prismic.TitleField;

  /**
   * Service Description field in *HomeServices → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_services.default.primary.services[].service_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_description: prismic.RichTextField;
}

/**
 * Primary content in *HomeServices → Default → Primary*
 */
export interface HomeServicesSliceDefaultPrimary {
  /**
   * title field in *HomeServices → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_services.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Header field in *HomeServices → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_services.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;

  /**
   * Image field in *HomeServices → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_services.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Services field in *HomeServices → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_services.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<Simplify<HomeServicesSliceDefaultPrimaryServicesItem>>;
}

/**
 * Default variation for HomeServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeServices*
 */
type HomeServicesSliceVariation = HomeServicesSliceDefault;

/**
 * HomeServices Shared Slice
 *
 * - **API ID**: `home_services`
 * - **Description**: HomeServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeServicesSlice = prismic.SharedSlice<"home_services", HomeServicesSliceVariation>;

/**
 * Primary content in *HomeTestimonies → Default → Primary*
 */
export interface HomeTestimoniesSliceDefaultPrimary {
  /**
   * Header field in *HomeTestimonies → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_testimonies.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;

  /**
   * content field in *HomeTestimonies → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_testimonies.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Link field in *HomeTestimonies → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_testimonies.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for HomeTestimonies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTestimoniesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeTestimoniesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeTestimonies*
 */
type HomeTestimoniesSliceVariation = HomeTestimoniesSliceDefault;

/**
 * HomeTestimonies Shared Slice
 *
 * - **API ID**: `home_testimonies`
 * - **Description**: HomeTestimonies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTestimoniesSlice = prismic.SharedSlice<
  "home_testimonies",
  HomeTestimoniesSliceVariation
>;

/**
 * Primary content in *PorfolioHeader → Default → Primary*
 */
export interface PorfolioHeaderSliceDefaultPrimary {
  /**
   * Header field in *PorfolioHeader → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: porfolio_header.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;
}

/**
 * Default variation for PorfolioHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PorfolioHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PorfolioHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PorfolioHeader*
 */
type PorfolioHeaderSliceVariation = PorfolioHeaderSliceDefault;

/**
 * PorfolioHeader Shared Slice
 *
 * - **API ID**: `porfolio_header`
 * - **Description**: PorfolioHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PorfolioHeaderSlice = prismic.SharedSlice<
  "porfolio_header",
  PorfolioHeaderSliceVariation
>;

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<"projects", ProjectsSliceVariation>;

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<"services", ServicesSliceVariation>;

/**
 * Primary content in *ServicesHeader → Default → Primary*
 */
export interface ServicesHeaderSliceDefaultPrimary {
  /**
   * Header field in *ServicesHeader → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: services_header.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;

  /**
   * Pitch field in *ServicesHeader → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: services_header.default.primary.pitch
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pitch: prismic.TitleField;
}

/**
 * Default variation for ServicesHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesHeader*
 */
type ServicesHeaderSliceVariation = ServicesHeaderSliceDefault;

/**
 * ServicesHeader Shared Slice
 *
 * - **API ID**: `services_header`
 * - **Description**: ServicesHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesHeaderSlice = prismic.SharedSlice<
  "services_header",
  ServicesHeaderSliceVariation
>;

/**
 * Default variation for Testimonies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimoniesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Testimonies*
 */
type TestimoniesSliceVariation = TestimoniesSliceDefault;

/**
 * Testimonies Shared Slice
 *
 * - **API ID**: `testimonies`
 * - **Description**: Testimonies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimoniesSlice = prismic.SharedSlice<"testimonies", TestimoniesSliceVariation>;

/**
 * Primary content in *TestimoniesHeader → Default → Primary*
 */
export interface TestimoniesHeaderSliceDefaultPrimary {
  /**
   * Header field in *TestimoniesHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies_header.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;
}

/**
 * Default variation for TestimoniesHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimoniesHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimoniesHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimoniesHeader*
 */
type TestimoniesHeaderSliceVariation = TestimoniesHeaderSliceDefault;

/**
 * TestimoniesHeader Shared Slice
 *
 * - **API ID**: `testimonies_header`
 * - **Description**: TestimoniesHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimoniesHeaderSlice = prismic.SharedSlice<
  "testimonies_header",
  TestimoniesHeaderSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      CasestudiesDocument,
      CasestudiesDocumentData,
      CasestudiesDocumentDataSlicesSlice,
      CasestudyDocument,
      CasestudyDocumentData,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ServiceDocument,
      ServiceDocumentData,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      TestimonialDocument,
      TestimonialDocumentData,
      TestimoniesDocument,
      TestimoniesDocumentData,
      TestimoniesDocumentDataSlicesSlice,
      AllDocumentTypes,
      CaseStudiesSlice,
      CaseStudiesSliceVariation,
      CaseStudiesSliceDefault,
      CaseStudyHeaderSlice,
      CaseStudyHeaderSliceDefaultPrimary,
      CaseStudyHeaderSliceVariation,
      CaseStudyHeaderSliceDefault,
      ContactFormSlice,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ContactHeroSlice,
      ContactHeroSliceDefaultPrimary,
      ContactHeroSliceVariation,
      ContactHeroSliceDefault,
      ContactTimelineSlice,
      ContactTimelineSliceVariation,
      ContactTimelineSliceDefault,
      HomeContactFormSlice,
      HomeContactFormSliceVariation,
      HomeContactFormSliceDefault,
      HomeHeroSlice,
      HomeHeroSliceDefaultPrimary,
      HomeHeroSliceVariation,
      HomeHeroSliceDefault,
      HomeProjectsSlice,
      HomeProjectsSliceDefaultPrimary,
      HomeProjectsSliceVariation,
      HomeProjectsSliceDefault,
      HomeServicesSlice,
      HomeServicesSliceDefaultPrimaryServicesItem,
      HomeServicesSliceDefaultPrimary,
      HomeServicesSliceVariation,
      HomeServicesSliceDefault,
      HomeTestimoniesSlice,
      HomeTestimoniesSliceDefaultPrimary,
      HomeTestimoniesSliceVariation,
      HomeTestimoniesSliceDefault,
      PorfolioHeaderSlice,
      PorfolioHeaderSliceDefaultPrimary,
      PorfolioHeaderSliceVariation,
      PorfolioHeaderSliceDefault,
      ProjectsSlice,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      ServicesSlice,
      ServicesSliceVariation,
      ServicesSliceDefault,
      ServicesHeaderSlice,
      ServicesHeaderSliceDefaultPrimary,
      ServicesHeaderSliceVariation,
      ServicesHeaderSliceDefault,
      TestimoniesSlice,
      TestimoniesSliceVariation,
      TestimoniesSliceDefault,
      TestimoniesHeaderSlice,
      TestimoniesHeaderSliceDefaultPrimary,
      TestimoniesHeaderSliceVariation,
      TestimoniesHeaderSliceDefault,
    };
  }
}
