// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  case_studies: dynamic(() => import("./CaseStudies")),
  case_study_header: dynamic(() => import("./CaseStudyHeader")),
  contact_form: dynamic(() => import("./ContactForm")),
  contact_hero: dynamic(() => import("./AboutHero")),
  contact_timeline: dynamic(() => import("./AboutTimeline")),
  home_contact_form: dynamic(() => import("./HomeContactForm")),
  home_hero: dynamic(() => import("./HomeHero")),
  home_projects: dynamic(() => import("./HomeProjects")),
  home_services: dynamic(() => import("./HomeServices")),
  home_testimonies: dynamic(() => import("./HomeTestimonies")),
  porfolio_header: dynamic(() => import("./PorfolioHeader")),
  projects: dynamic(() => import("./Projects")),
  services: dynamic(() => import("./Services")),
  services_header: dynamic(() => import("./ServicesHeader")),
  testimonies: dynamic(() => import("./Testimonies")),
  testimonies_header: dynamic(() => import("./TestimoniesHeader")),
};
